<?php
//BEGÄRA $_POST KOLLA EFTER FÖDELSEDTAN I POST DATAN. RÄKNA UT VILKET HOROSCOPE FÖDELSEDATUMET TILLHÖR OCH UPPDATERA DET SPARADE HOROSOPET TILL SOM FINNS I $_SESSION OCH SKRIV 

function testsomething(){
    return "en Sträng";
}

?>